widgets_demo/config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :products do
    member do
      get :widget
    end
  end
  get '/get_product_form' => 'products#get_product_form'
  post '/save_product' => 'products#create'
  get '/widget' => 'products#widget'

  root 'products#index'

end

widgets_demo/app/models/product.rb
class Product < ActiveRecord::Base
end

widgets_demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

widgets_demo/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :allow_iframe_requests
  def allow_iframe_requests
    response.headers.delete('X-Frame-Options')
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  def widget
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

 
  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
      if @product.blank?
        @product = Product.first
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :type, :quality)
    end
end

widgets_demo/app/helpers/application_helper.rb
module ApplicationHelper
end

widgets_demo/app/helpers/products_helper.rb
module ProductsHelper
end

widgets_demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WidgetsDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

widgets_demo/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quality %><br>
    <%= f.text_field :quality %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

widgets_demo/app/views/products/destroy.js.erb
var id = <%= @product.id.to_s %>;
$('#'+id).remove();
iframe_obj.triggerDeleteEvenet();

widgets_demo/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

widgets_demo/app/views/products/get_product_form.js.erb
var url = '<%= new_product_url %>';
var $iframe = $('#testFrame');
console.log($iframe)
$iframe.context.URL = url; 
console.log($iframe)

widgets_demo/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quality</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr id= "<%= product.id %>" >
        <td><%= product.name %></td>
        <td><%= product.quality %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Product', new_product_path %>

widgets_demo/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

widgets_demo/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @product.type %>
</p>

<p>
  <strong>Quality:</strong>
  <%= @product.quality %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

widgets_demo/app/views/products/widget.html.erb
<h3><b>Product</b></h3>
<% @products.each do |product| %>
	<h3>Name: <%= product.name %></h3>
	<h3>Qulaity: <%= product.quality %></h3>
<% end %>
<%= link_to 'Add new product', get_product_form_url, id: "new_product", remote: true %>

widgets_demo/app/views/products/widget.js.erb
$('#frame_div').html("<%= escape_javascript(content_tag(:iframe,'', width: 560, height: 315, id: 'testFrame', :src => products_url)).html_safe%>");